<?php
$sessions = array(
    '2013' => array(
        'last_timestamp' => time(),
        'sessions' => array(
            array(
                'speaker' => 'Allen Own & Orange Tsai',
                'subject' => 'PHP 網站攻防實務',
                'description' => '在網路資訊安全越顯重要的今天，您如何保護您的網站資料不被竊取呢？瞭解駭客的心理與技術，瞭解網站程式有何漏洞，都是現在 Web 開發必須熟知的課題。這次， PHPConf 邀請到了 Allen Own 與 Orange Tsai 兩位台灣資安界的高手，他們將透過精心設計的攻防實戰，告訴大家資安的重要性！',
                'start_time' => '09:30',
                'end_time' => '10:20',
                'room' => 'r0',
                'slide_url' => '',
                'video_url' => '',
            ),
            array(
                'speaker' => 'Phalcon Kernel',
                'subject' => 'Racklin',
                'description' => '效能問題在 PHP 上一直都是很值得探討的議題，而提升執行效能的其中一種方法，就是將關鍵部份以 C 來開發；可是 PHP Extension 的開發對一般開發者來說，門檻相當高；因此 PHPConf 邀請到了技術界人稱阿土伯的 Rack Lin ，他將介紹如何透過 Phalcon Framework 的核心，開發屬於自己的 PHP Extension ！',
                'start_time' => '10:30',
                'end_time' => '11:10',
                'room' => 'r0',
                'slide_url' => '',
                'video_url' => '',
            ),
            array(
                'speaker' => 'Rex',
                'subject' => 'Evernote SDK for PHP - 你所不知的 Evernote',
                'description' => 'Evernote 是個雲端筆記的服務，但是為什麼講者的免費版功能比專業版還多呢？本議程將讓你快速了解如何開始使用 Evernote SDK for PHP ，從開發者的角度來介紹如何使用 Evernote ，來幫助你讓生活變得更輕鬆；並且也將介紹在整合 Evernote 時的 Best Practices 。',
                'start_time' => '10:30',
                'end_time' => '11:10',
                'room' => 'r2',
                'slide_url' => '',
                'video_url' => '',
            ),
            array(
                'speaker' => 'Tsung',
                'subject' => 'Big Data in SiteTag',
                'description' => '當網站規模逐漸擴大時，開發者就一定會面臨到大流量、大資料量的處理。而在台灣，這樣的環境與經驗通常只掌握在大型企業手中，一般開發者很少能接觸到。 PHPConf 這次邀請到 tsung ，他將透過開發 SiteTag 的經驗，來為大家說明如何處理巨量資料。',
                'start_time' => '11:20',
                'end_time' => '12:00',
                'room' => 'r0',
                'slide_url' => '',
                'video_url' => '',
            ),
            array(
                'speaker' => 'kiang',
                'subject' => 'MagentoCommerce Extension 開發',
                'description' => 'MagentoCommerce 是目前 (2013.02) 世界流量前百萬個網站中，最被廣泛使用的電子商務系統 (參考： http://twpug.net/modules/newbb/viewtopic.php?topic_id=7347) ，基於 Zend Framework 1 開發。不過因為架構龐大且公開文件稀少與版本混亂，讓它的學習曲線異常陡峭。透過這個主題希望能夠提供敲門磚給更多朋友，學習這個難得的電子商務系統典範。',
                'start_time' => '11:20',
                'end_time' => '12:00',
                'room' => 'r2',
                'slide_url' => '',
                'video_url' => '',
            ),
            array(
                'speaker' => 'appleboy (吳柏毅)',
                'subject' => '用 Gearman 及 CodeIgniter 打造 PHP 排程系統',
                'description' => '還在使用 Linux Cron 或 Windows 排程處理大量縮圖、發送簡訊、寄送信件...等耗費系統資源的工作嗎？本議程將為大家介紹 Gearman Application Framework 在 CodeIgniter 上幫助您處理大量工作。',
                'start_time' => '13:00',
                'end_time' => '13:40',
                'room' => 'r0',
                'slide_url' => '',
                'video_url' => '',
            ),
            array(
                'speaker' => 'Jimmy',
                'subject' => '進擊的快取',
                'description' => '快取策略百百種，從 Server 端的頁面與程式快取，到應用程式端的各式資料媒介快取...到底哪些是必用、有效的、合用的？面對多種使用情境，又如何處理快取建置與過期問題？本議程的講者將分享肥胖的 Drupal 是如何利用其快取架構，消脂成功上戰場；而又容易碰到哪些問題，讓快取的效能、合用性不佳。透過講者在 Drupal 上的經驗，相信能讓 PHP 開發者們在建構自己的應用程式時有所啟發。',
                'start_time' => '13:00',
                'end_time' => '13:40',
                'room' => 'r2',
                'slide_url' => '',
                'video_url' => '',
            ),
            array(
                'speaker' => 'Jonathan Maron',
                'subject' => '5 Easy Ways To Speed Up Your Web Application',
                'description' => 'There are hundreds of ways by which a developer can increase the technical and perceived speed of a web application. Some are complicated to implement and improve performance by only a minimal amount, whereas others are easy to implement and increase performance by a large factor. These so called ""Low-Hanging Fruits"" are the subject of this talk. The presentation discusses five easily implemented, practical measures to increase performance with minimum changes to existing code.',
                'start_time' => '13:45',
                'end_time' => '14:25',
                'room' => 'r0',
                'slide_url' => '',
                'video_url' => '',
            ),
            array(
                'speaker' => 'Alansun',
                'subject' => 'Slim 從零開始',
                'description' => '越來越多 PHP Framework 如雨後春筍冒出，各種 MVC 架構功能相當的強大，卻也導致了使用 Framework 必須得付出一定的代價。本議程中，講者將介紹 Slim 這個以輕薄、快速、簡易功能著稱的 PHP Framework ；並介紹如何以 Slim 來快速架構出網站雛形，或是建置臨時性的網站服務或短期活動頁面。',
                'start_time' => '13:45',
                'end_time' => '14:25',
                'room' => 'r2',
                'slide_url' => '',
                'video_url' => '',
            ),
            array(
                'speaker' => 'c9s',
                'subject' => 'AssetToolkit 簡介與應用',
                'description' => 'JavaScript 、 CSS 等這類前端檔案的最小化及相依性管理，常是 Web 開發者頭痛的問題之一。雖然可以借助 Framework 來處理，但也相對地要讓程式碼綁死在 Framework 上面。 PHPConf 邀請到台灣 PHP 界的第一把交椅 c9s ，他將為大家介紹他自己設計的工具： AssetToolkit ，來更有效率地管理前端檔案。',
                'start_time' => '14:30',
                'end_time' => '15:10',
                'room' => 'r0',
                'slide_url' => '',
                'video_url' => '',
            ),
            array(
                'speaker' => 'Benjamin Peng (波卡 Poka)',
                'subject' => '從 CodeIgniter 跳槽到 Laravel',
                'description' => '在本議程中，講者將以自己的經驗和常見的需求案例，談談在多變的客戶需求下， CodeIgniter 所謂零設定的框架架構將會帶來什麼樣的困擾，以及切換到 Laravel 之後，將如何更有效率地解決這些問題。',
                'start_time' => '14:30',
                'end_time' => '15:10',
                'room' => 'r2',
                'slide_url' => '',
                'video_url' => '',
            ),
            array(
                'speaker' => 'Jace Ju',
                'subject' => 'Composer 入門',
                'description' => '',
                'start_time' => '15:30',
                'end_time' => '16:10',
                'room' => 'r0',
                'slide_url' => '',
                'video_url' => '',
            ),
            array(
                'speaker' => 'Ricky',
                'subject' => 'PHP 也可以很 event - 用 PHP 打造一個 Realtime Web',
                'description' => 'PHP 給人的印象往往是無法在大流量下做到即時反應，而且離不開 Apache Web Server 。講者將說明 PHP 只要透過 event extension ，也可以用來處理大量連線問題。並針對 comet 技術與 c10k 問題作逐一的探討。',
                'start_time' => '15:30',
                'end_time' => '16:10',
                'room' => 'r2',
                'slide_url' => '',
                'video_url' => '',
            ),
        ),
    ),
    '2012' => array(
        'last_timestamp' => time(),
        'sessions' => array(
            array(
                'speaker' => '',
                'subject' => '',
                'description' => '',
                'start_time' => '',
                'end_time' => '',
            ),
        )
    ),
    '2011' => array(
        'last_timestamp' => time(),
        'sessions' => array(
            array(
                'speaker' => '',
                'subject' => '',
                'description' => '',
                'start_time' => '',
                'end_time' => '',
            ),
        )
    ),
);

echo json_encode($sessions, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);